### ISSUE TITLE
[Suggestion] Close the emotes menu using the same key

### ISSUE THREAD

**Issue by Filiaes** [Scullyy/dpemotes#4]
Hi, please add an option to close the menu with F5. Actually it stays on the screen. Beside that, when I escape the map opens. Would be fine to quit the menu with esc too if the map doesn't open.

**Comment by Scullyy** [comment]
Please make your suggestion to ox_lib, this is unrelated to the emote menu.

**Comment by Filiaes** [comment]
What about https://overextended.github.io/docs/ox_lib/Interface/Client/menu/#libhidemenu ?

**Comment by Scullyy** [comment]
Added in https://github.com/Scullyy/dpemotes/commit/9395c36f86f248cb5cd6a42b1066ca5305ac2ef5
