### ISSUE TITLE
Cop Emotes

### ISSUE THREAD

**Issue by TheCrypticOG** [Scullyy/dpemotes#5]
Hey there! I noticed that the first 4 cop emotes, and the last cop emote are not working. (At least for me). When you click them nothing happens but the other ones appear to be working great!

**Comment by Scullyy** [comment]
The walk styles are just walk styles, you need to walk around to notice them. Make sure you’re on the latest version also as some broken emotes were removed in a previous update. There is only 4 cop walk styles.
